language: php

php:
  - '7.0'
  - '7.1'

before_script:
  - composer install

script:
  - docker run -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose .
  - docker run -v $PWD:/app phpqa/security-checker security:check
#  - docker run -v $PWD:/app phpqa/phpcs .

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: heroku
  api_key:
    secure: "6af5ac98-1caf-4a69-8b70-b7f3d3c65aa4"
  app: michaelesgi
  on:
    repo: Asiatiks/esgi
    branch: master